### ISSUE TITLE
WebMC crash on start

### ISSUE THREAD

**Issue by x-0D** [Ratcoder/WebMC#2]
When i try to create new user and (after ELUA accept) server download screen appears, it crashes

```js
(node:9128) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at C:\webmc-0.1.3\app\setup.js:113:93
    at ChildProcess.exithandler (child_process.js:310:7)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\webmc-0.1.3\mc\bedrock-server\bedrock_server.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\webmc-0.1.3\\mc\\bedrock-server\\bedrock_server.exe',
  path: 'C:\\webmc-0.1.3\\mc\\bedrock-server\\bedrock_server.exe',
  spawnargs: []
}

[процесс завершил работу с кодом 1 (0x00000001)]```

**Comment by Lekos555** [comment]
I take it the project is dead? For instead of the archive with the server, only XML is downloaded:
```
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:a52bc876-901e-0166-71a9-adc2d9000000
Time:2023-07-03T12:22:19.4407820Z</Message></Error>
```

**Comment by 10ij** [comment]
I think this is because microsoft changed the download stucture so the app has to updated for their new url format
